routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();


Route::middleware('auth')->group(function () {
    Route::prefix('dashboard')->group(function () {
        Route::get('home', 'DashboardController@versionone')->name('home');
        Route::get('v2', 'DashboardController@versiontwo')->name('v2');
        Route::get('v3', 'DashboardController@versionthree')->name('v3');

        Route::post('dashboard_charts', 'DashboardController@DashboardCharts')->name('dashboard_charts');
    });

    Route::prefix('messages')->as('messages.')->group(function () {
        Route::get('/', 'MessageController@index')->name('index');
        Route::post('save', 'MessageController@save')->name('save');
        Route::post('delete', 'MessageController@delete')->name('delete');
    });

    Route::resource('organizations', 'OrganizationController');
    Route::resource('statuses', 'StatusesController');
    Route::resource('admins', 'AdminController');
    Route::resource('users', 'UsersController');
});


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

resources/views/admin/create.blade.php
@extends('layouts.master')


@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>@lang('general.user_creating')</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('general.dashboard')</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admins.index') }}">@lang('general.admins')</a></li>
                            <li class="breadcrumb-item active">@lang('general.create')</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <section class="content">
            {!! Form::model($user, [
                'route' => ['admins.store'],
                'method' => 'post',
                'files' => true,
                'id' => 'user_create_form'
            ]) !!}
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">@lang('general.users')</h3>
                    <div class="card-tools">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success', 'form' => 'user_create_form']) !!}
                    </div>
                </div>
                <div class="card-body">
                    @include('admin.partials.form')
                    {!! Form::hidden('created_by', Auth::id()) !!}
                </div>
            </div>

        </section>
    </div>
    <div class="row">
        <div class="col-md-12">

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success']) !!}

                        <a href="{{ route('users.index') }}" class="btn btn-default"><i class="fa fa-share"></i></a>
                    </div>
                </div>
                <div class="box-body">

                </div>
            </div>

        </div>
    </div>
@endsection

@section('javascript')
    <script>
        $(function () {

            function randString(id){
                var dataSet = $(id).attr('data-character-set').split(',');
                var possible = '';
                if($.inArray('a-z', dataSet) >= 0){
                    possible += 'abcdefghijklmnopqrstuvwxyz';
                }
                if($.inArray('A-Z', dataSet) >= 0){
                    possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                }
                if($.inArray('0-9', dataSet) >= 0){
                    possible += '0123456789';
                }
                if($.inArray('#', dataSet) >= 0){
                    possible += '![]{}()%&*$#^<>~@|';
                }
                var text = '';
                for(var i=0; i < $(id).attr('data-size'); i++) {
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }
                return text;
            }

            // Create a new password
            $(".getNewPass").click(function(){
                var field = $(this).closest('div').find('input[rel="gp"]');
                var password = randString(field);
                field.val(password).prop("type", "text");
                $('input[rel="gp_confirm"]').val(password).prop("type", "text");
            });

            // Auto Select Pass On Focus
            $('input[rel="gp"]').on("click", function () {
                $(this).select();
            });


        });
    </script>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>@lang('general.edit_user')</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('general.dashboard')</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admins.index') }}">@lang('general.admins')</a></li>
                            <li class="breadcrumb-item active">@lang('general.edit')</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <section class="content">
            {!! Form::model($user,
                ['route' => ['admins.update',$user ],
                'method' => 'put',
                'files' => true,
                'id' => 'user_create_form'
            ]) !!}
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">@lang('general.users')</h3>
                    <div class="card-tools">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success', 'form' => 'user_create_form']) !!}
                    </div>
                </div>
                <div class="card-body">
                    @include('admin.partials.form')
                    {!! Form::hidden('modified_by', Auth::id()) !!}
                </div>
            </div>

        </section>
    </div>
@endsection

@section('javascript')
    <script>
        $(function () {

            function randString(id){
                var dataSet = $(id).attr('data-character-set').split(',');
                var possible = '';
                if ($.inArray('a-z', dataSet) >= 0) {
                    possible += 'abcdefghijklmnopqrstuvwxyz';
                }
                if ($.inArray('A-Z', dataSet) >= 0) {
                    possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                }
                if ($.inArray('0-9', dataSet) >= 0) {
                    possible += '0123456789';
                }
                if ($.inArray('#', dataSet) >= 0) {
                    possible += '![]{}()%&*$#^<>~@|';
                }
                var text = '';
                for (var i=0; i < $(id).attr('data-size'); i++) {
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }
                return text;
            }

            // Create a new password
            $(".getNewPass").click(function(){
                var field = $(this).closest('div').find('input[rel="gp"]');
                var password = randString(field);
                field.val(password).prop("type", "text");
                $('input[rel="gp_confirm"]').val(password).prop("type", "text");
            });

            // Auto Select Pass On Focus
            $('input[rel="gp"]').on("click", function () {
                $(this).select();
            });


        });
    </script>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>@lang('general.users')</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">@lang('general.home')</a></li>
                            <li class="breadcrumb-item active">@lang('general.admins')</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">@lang('general.users')</h3>

                    <div class="card-tools">
                        <a href="{{ route('admins.create') }}" class="btn btn-sm btn-success add_new_user">
                            @lang('general.new')
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <form class="" action="" method="get">

                        @if (request()->page)
                            <input type="hidden" value="{{ request()->page }}" name="page" />
                        @endif

                        @if (request()->sort)
                            <input type="hidden" value="{{ request()->sort }}" name="sort" />
                        @endif

                        @if (request()->order)
                            <input type="hidden" value="{{ request()->order }}" name="order" />
                        @endif

                        <div class="card mt-3">
                            <div class="card-header">
                                <h3 class="card-title">Filter</h3>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group row">
                                            <label class="col-form-label col-sm-4 text-right" >Profile registered</label>
                                            <div class="col-sm-8">
                                               <input placeholder="Registered from" class="form-control datepicker" type="text" name="created_from"
                                                    value="{{ request()->created_from }}" />
                                                <input placeholder="Registered till" class="form-control datepicker"  type="text" name="created_to"
                                                       value="{{ request()->created_to }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12 text-right">
                                        <button type="submit" class="btn btn-primary">Search</button>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </form>
                    <table class="table table-hover table-striped table-bordered table-condensed responsive">
                        <thead>
                        <tr>
                            @foreach (['user', 'email'] as $column)
                            <th>
                                <a href="{{ route('admins.index', $request->merge([
                                    'sort' => request()->order == $column && request()->sort == 'ASC' ? 'DESC' : 'ASC',
                                    'order' => $column
                                ])->all()) }}">
                                    @lang('general.' . $column)
                                </a>
                            </th>
                            @endforeach
                            <th>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($users as $user)
                            <tr>
                                <td data-label="@lang('general.user')">{{ $user->name }}</td>
                                <td data-label="@lang('general.email')">{{ $user->email }}</td>
                                <td class="td-action">
                                    <a href="{{ route('admins.edit', $user) }}" class="float-sm-left d-inline-block d-sm-inline btn btn-success btn-sm pull-left">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    @if($user->id != 1)
                                    <form class="float-sm-left ml-2 d-inline-block d-sm-inline" onsubmit="if(confirm('@lang('general.deleting')')){ return true }else{ return false }" action="{{ route('admins.destroy', $user) }}" method="post">
                                        <input type="hidden" name="_method" value="delete" />
                                        {{csrf_field()}}
                                        <button type="submit" class="btn-sm remove_item btn btn-danger pull-left"><i class="fa fa-trash"></i></button>
                                    </form>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center">
                                    <b>@lang('general.empty_data')</b>
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                    <div class="col-sm-12 text-center">
                        <nav aria-label="page navigation" class="justify-content-center mt-3">
                            {{ $users->appends(request()->except('page'))->links() }}
                        </nav>
                    </div>

                </div>
            </div>

        </section>
    </div>
@endsection